name: DEV Publish packages to NPM
on:
  workflow_call:
    inputs:
      NPM_TAG:
        required: true
        type: string
      GIT_BRANCH:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'


