name: DEV Upload plugins dockers
on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🔧 Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: 🔧 Set up AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 🔧 Compile all dockers
        run: bash scripts/build_dockers_by_folder.sh ./plugins

      - name: 🔧 Upload all dockers to ECR
        run: bash scripts/push_dockers_to_aws_by_folder.sh ./plugins

