name: DEV Upload plugins dockers
on:
  push:
    tags:
      - '*.*.*-mdevdockers'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Mostrar Tag
        run: echo "El tag es ${{ github.ref_name }}"
