name: DEV Publish packages & publish dockers
on:
  push:
    tags:
      - '*.*.*-mdev'

jobs:
  publish_packages_to_npm:
    uses: ./.github/workflows/dev-packages-to-npm.yml
    with:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  build_and_publish_dockers:
    needs: publish_packages_to_npm
    uses: ./.github/workflows/dev-upload-plugins-dockers.yml

