name: Get packages and plugins modified
on:
  workflow_call:
    inputs:
      tag_pattern:
        required: true
        type: string
    outputs:
      packages:
        description: "Modified packages"
        value: ${{ jobs.publish.outputs.packages }}
      plugins:
        description: "Modified plugins"
        value: ${{ jobs.publish.outputs.plugins }}

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:

      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: 📝 Get modified files
        id: files
        run: |
          LAST_TAG=git tag -l '${{ inputs.tag_pattern }}' | sort -V | tail -n 2 | head -n 1
          CURRENT_TAG=git tag -l '${{ inputs.tag_pattern }}' | sort -V | tail -n 1 | head -n 1
          echo "::set-output name=packages::$(git diff --name-only $LAST_TAG $CURRENT_TAG | grep '^packages/')"
          echo "::set-output name=plugins::$(git diff --name-only $LAST_TAG $CURRENT_TAG | grep '^plugins/')"




