name: Get packages and plugins modified
on:
  workflow_call:
    inputs:
      tag_pattern:
        required: true
        type: string
    outputs:
      packages:
        description: "Modified packages"
        value: ${{ jobs.publish.outputs.packages }}
      plugins:
        description: "Modified plugins"
        value: ${{ jobs.publish.outputs.plugins }}

jobs:
  publish:

    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
      plugins: ${{ steps.plugins.outputs.plugins }}
    steps:

      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: 🔧 Get last tag
        run: LAST_TAG=$(git tag -l '${{ inputs.tag_pattern }}' | sort -V | tail -n 2 | head -n 1)

      - name: 🔧 Get current tag
        run: CURRENT_TAG=$(git tag -l '${{ inputs.tag_pattern }}' | sort -V | tail -n 1 | head -n 1)
        
      - name: 🔧 Get packages files
        id: packages
        run:  echo "packages=$(git diff --name-only $LAST_TAG $CURRENT_TAG | grep '^packages/')" >> $GITHUB_OUTPUT

      - name: 🔧 Get plugins files
        id: plugins
        run:  echo "plugins=$(git diff --name-only $LAST_TAG $CURRENT_TAG | grep '^plugins/')" >> $GITHUB_OUTPUT

      - name: 🔧 Log
        run:  echo ${LAST_TAG}

      - name: 🔧 Log
        run:  echo ${CURRENT_TAG}

      - name: 🔧 Log
        run:  'echo "Modified packages: " "${{ steps.packages.outputs.packages }}"'

      - name: 🔧 Log
        run:  'echo "Modified plugins: " "${{ steps.plugins.outputs.plugins }}"'

